# Generated by Django 4.0.4 on 2022-05-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('has_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_status', models.CharField(choices=[('IN', 'Inacabado'), ('NO', 'Novo'), ('RE', 'Reassistir')], default='NO', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('streaming_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_film_list.streamingservice')),
            ],
        ),
    ]
