# Generated by Django 4.0.4 on 2022-05-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_film_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraCinematografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_obra_cinematografica', models.CharField(choices=[('IN', 'Inacabado'), ('NO', 'Novo'), ('RE', 'Reassistir')], default='NO', max_length=10)),
                ('type_obra_cinematografica', models.CharField(choices=[('FI', 'Filme'), ('SE', 'Seriado')], default='SE', max_length=7)),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('streaming_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_film_list.streamingservice')),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
    ]
